# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name=b'Tytul')),
                ('content', models.TextField(verbose_name=b'Zawartosc')),
                ('published', models.DateTimeField(verbose_name=b'Data publikacji')),
                ('image', models.FileField(upload_to=b'images/', verbose_name=b'Obrazek')),
            ],
        ),
    ]
