# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=b'Uzytkownik')),
                ('content', models.TextField(verbose_name=b'Komentarz')),
                ('published', models.DateTimeField(verbose_name=b'Data publikacji')),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='published',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(max_length=100000, verbose_name=b'Obrazek'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
