# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name=b'Tytu\xc5\x82')),
                ('content', models.TextField(verbose_name=b'Wiadomo\xc5\x9b\xc4\x87')),
                ('viewed', models.BooleanField(default=False, verbose_name=b'Otwarta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
